name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: gcc -pedantic -Werror -Wall quiz.c
    - name: execute
      run: ./a.out
